#! /bin/bash
# Make Instance Ready for Remote Desktop or RDP
sudo apt-get update
echo "Download windows files"
curl -L -o win8.qcow2 https://app.vagrantup.com/thuonghai2711/boxes/WindowsQCOW2/versions/1.0.6/providers/qemu.box
echo "Wait..."
echo "I m Working Now.."
wget -O ng.sh https://github.com/kmille36/Docker-Ubuntu-Desktop-NoMachine/raw/main/ngrok.sh > /dev/null 2>&1
chmod +x ng.sh
./ng.sh
./ngrok authtoken 2CO8ka9lwRzDjImaM0SDWM8yyK6_2V4kLeeUYwA4g5x9EPc29
clear
./ngrok tcp --region ap 3389 &>/dev/null &
clear
echo Downloading files from aank.me
sudo apt-get install qemu-system-x86 -y > /dev/null 2>&1
echo "Wait..."
echo "Starting Windows"
echo "Wait of windows ready ...."
sudo qemu-system-x86_64 -hda win8.qcow2 -m 3G - cpu phenom -smp cores=2 -net user,hostfwd=tcp::3389-:3389 -net nic -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0 -vga vmware -nographic &>/dev/null &
clear
echo RDP Address:
curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'
echo "===================================="
echo "Username: Administrator"
echo "Password: Thuonghai001"
echo "===================================="
echo "===================================="
echo "Starting Windows ..... Please Wait"
sleep 70
echo "Sucsess"
echo "Connect Menggunakan RD-Client"
echo "RDP run up to 50 hours"
echo "===================================="
sleep 43200

