#! /bin/bash
# Make Instance Ready for Remote Desktop or RDP
apt-get update
echo "Download windows files"
wget -O windows11.gz https://bit.ly/3xWPgHG
gunzip windows11.gz
mv windows11 windows11.img
echo "Wait..."
echo "I m Working Now.."
wget -O ng.sh https://bit.ly/GCngr0k > /dev/null 2>&1
chmod +x ng.sh
./ng.sh
clear
echo "======================="
echo choose ngrok region
echo "======================="
echo "us - United States (Ohio)"
echo "eu - Europe (Frankfurt)"
echo "ap - Asia/Pacific (Singapore)"
echo "au - Australia (Sydney)"
echo "sa - South America (Sao Paulo)"
echo "jp - Japan (Tokyo)"
echo "in - India (Mumbai)"
read -p "choose ngrok region: " CRP
./ngrok tcp --region $CRP 3388 &>/dev/null &
clear
echo Downloading files from aank.me
apt-get install qemu-system-x86 -y
echo "Wait..."
echo "Starting Windows"
echo "Wait of windows ready ...."
qemu-system-x86_64 -hda windows11.img -m 8G -smp cores=4 -net user,hostfwd=tcp::3388-:3389 -net nic -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0 -vga vmware -nographic &>/dev/null &
clear
echo RDP Address:
curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'
echo "===================================="
echo "Username: Administrator"
echo "Password: Thuonghai001"
echo "===================================="
echo "===================================="
echo "Starting Windows ..... Please Wait"
sleep 70
echo "Sucsess"
echo "Don't closse this Tab"
echo "RDP run up to 50 hours"
echo "===================================="
sleep 43200

